# Environment ----------------

notifications:
  email:
    on_success: never
    on_failure: change

sudo: false
language: python

cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

env:
  global:
    secure: 1r59yROi+33PcYR+hCo8eYw18UuecDXRE2L/YLufJz13oBLp6wlZMvvyp4rrf+EPBvbgTi86ACRGLa4c3/YIgxkffHW8LNBRdGQXk+A8nrJOsL+6xzDlF4nwkggSMJI2ZLk6MNye4QtNBsoLhdyHLaO2VC4sAANJLk06e+atXfNzAaIv8vcxZcUXnklLBUz0ZR2uOaYB0ztiuDQNjjQWRB0IFkOKi76s95EYu9Ta/JgIk2UIojMwldB82EF75TMjpl2upvc92b++hfhSjGZKG5cm4bfbPQYN4HSqjycfdi886eRwkvs8z1vhveoHVDq9sqyr28s8636xvtAHy6fqOaTc8LMqTObHcpEhFGi3jH8cH3Ws4PQRlde146DYp4n9XIKpsAURMFIx6n8fA/tDH+pVmNrKim7gfZ++EQpPQT9quP4TBwrO8uZoo5wq0uJEry7TSgdIeAUFVFqeAcFPqhngF7j+pdbja4OB99EMHWBkE/9X5HEfIhSZbp2fO4Zs1k2rCFg7KI0I+RjPtZ7Tdsk+XjqdTCNCk+Ts9xDCswCK6xf54DCbjDwdG2vpioxCS6ZObHjgCRUAZI1ew8+4k1XDtnLs6sIrO953Xe7r5bkAK2DtdpsIGDYRmZ9+9zgrwTyhyr0x/3lVu0EdMix9yT6T9ZDR/sbR81FQTFFW6fk=


# Build commands ----------------

before_install:
  - if [ -z "$GITHUB_ACCESS_TOKEN" ]; then echo "Environment requires access token" && exit 1; fi

install:
  - pip install -r dev-requirements.txt

after_success:
  - tox -e coverage-report


# Jobs / Stages ----------------

jobs:
  include:
    - stage: lint
      python: '3.6'
      script: make lint

    - stage: test
      python: '2.7'
      env: TOXENV=py27
      script: make test

    - stage: test
      python: '3.4'
      env: TOXENV=py34
      script: make test

    - stage: test
      python: '3.5'
      env: TOXENV=py35
      script: make test

    - stage: test
      python: '3.6'
      env: TOXENV=py36
      script: make test

    - stage: release
      python: 3.6
      script: skip  # Only run the deploy step
      before_install: skip
      after_success: skip
      before_deploy:
        - if [ -z "$TWINE_USERNAME" ]; then exit 1; fi
        - if [ -z "$TWINE_PASSWORD" ]; then exit 1; fi
        - if [ -z "$GITHUB_TAG_TOKEN" ]; then exit 1; fi
        - git config --global user.email "builds@travis-ci.com"
        - git config --global user.name "Travis CI"
        - pip install -r dev-requirements.txt
        - git status  # For debugging
      deploy:
        provider: script
        script: make release && git push --quiet https://mattduck:$GITHUB_TAG_TOKEN@github.com/mattduck/pytest-it.git --tags >/dev/null 2>&1
        on:
          branch: master
          tags: false
          condition: >
            `make assert_clean_git assert_new_pypi_version >/dev/null 2>/dev/null; echo $?` == 0
      after_deploy: pip install pytest-it --upgrade
      env:
        - secure: "3MFAF/eQLEJIdGYcEWpe1TbEAIUH9/lbaeDdG7obw6Tkwa8vwM0Ji8hvvUtn781qDpcoy0eLbkoUKxmTr06S9ipsj0e/WR4dNH+jOCfr04JJW4JSxFJGP80FFqh/zsIRvBJjCD/l4D22FkYSzLXTV9vM7v6gWvdPHhu/m0lTlF5DXDpOHDFXLi6m/2uEPpnAb+B64L0MQMR+2gk5kFi3ueOztXooXvNA+IR7gC/70TXwAUbpD9le9zi0bYVyfohDNdlgwgX5SFkGRyjFw3lTguRTFm/Nu4u/Ln+TwKIBoKf94IwJAiFgNsfTMGCXGVz689Z7SrqgvRmWKxrjkoS/MZ1+w7fE76t8udJeBYqAIzXZEawGDmRFWgUgEQk3ZdplA2j9eofm1NMnM4ZwWMh1zBG3sDzbqR09S0KjpoeMjgXQ2la8iw5noh0KPaGT9fz29fJpiRxkfvmAsT72QIQ6wmh2HBNuwMDXc/lJdWoPgRqOGxYOwLraCXnqLqVYA3tJkL2KkLur0iWBkaXS3yBVNvG/C/zY6o1J0ykhdwBA1B6o0Z5Q497lL4wqymJdvBw3Lg3bVYGCW/pjRkLNPQ2qgZ26BewIO0P8dNeXHJMs0FPVU/Ok2sfqoAc0igxSgAVN/nAkDf+cVSXZmHAKfOexcz+YjuiKsaXXiFJs6ZyE59E="
        - secure: "TCFcv8rBEpJUbrCzCuMA4cqTYehK+HOzZGEo3AhJ/cKXUhoNkLkJ4Jid0+7sKlfZw3BlASUNNt993StVzEIfePbJ4CwKJ2utUudhXFqlqFZx/vI3NUapo53oNB0NH3r+v1yyvDRJscy1AE24IIMSD2KtoaeDGAO8KLwZMhhgVsvSCnrHNma8F/QWKnPYA2gg1Wmj3iXxO7NHELwQRYSs3hfERUIv97Lf7gf5wjGDocrTsFcnHxAxgGC55obXymST4Wn9lKEqyKBQv/6WcYHaGrfRN42GZEbiSzY7XHyzsrj9dVBiU7vK47QsmIR9qW8MMFPiyHYLTtit3xeNzP6L9NuLphku/wDTrfR1OlAVd7H+kNcw4fnlF0ar3I6OL5KyvorNh3zKzs0WLmxRLi1NN1mkWVkoYbgGplmy9yjZ52VM8U2tJhUvrG1ZiDH9atWLvn+dcEK5k9yfXjJqmGh4L+5GtOJhGsiuNMg2IrFD4Ef8nXRNLJI22BSkmBK6pjZCKFHyxkb6EQkACm7PkjXKvQARlcpKaNjUMYrAdeZVDOumc6pOGL+jCuAmHclhh6rMiICPYlGmXAzIQcG8dPDlGfErhvRBV7oJQh3IPL4wk0YnmZ3a/OMPdG7mzL2UnVspN/YW0eMqaKuPWIxPey+ciWiH1Wrv9CNhCUCITxIg2ks="
        - secure: "nCZTIWN8aymv+wCVmBGgkBI8w5oYmsAJ1Y9oVjoIMWGGXxDg9uyuEB5tCo4k9adt4gEouTl3hjqTTTA4JUaiMJ/qkH3P3LzBW+JGXTvDNUkn4inAjF6FtWIsH1M4LF/VTTqdU41/DEfIeFcDfdg6xGUqcuSN2xxeO0HhRPhurH+4ljGQxkxva4LFwgklen/iHGqrQxUo+AMS0mN1oy4GZSkspQ9CBuBYcxAjsMjiGYbFryS3VNZe0jQGvsAnjKXOVKlywdZB6Fsu41MZYlEVarAJBiZKx82wF2oLdZWIfWbBTSB9qXfQgfapslBjUQHKQV73JcfMYiY6DLrUKRyZn48zFKSYoPuOF274ac7YUgxjaDP5Zj3RVlOpFHvaI3VWyxVJE1CpiKSBcPyP72xkXWmEk4CaFcsJbsiKreoDEUlLzFZ+DDL0rpDli/nB1N4xRvEvumFjIRQK252EnCH9uB1XF1VZLfyeQZ4MvoZLIUs2nE3GJqpO68KsftBU9i70XTczETH0JHRHSNjbUOlnovmanBbbjK3ts585UiTl6Y4Kp/J4vgeypfJlZsQ8BybF4bgsUe9BGC3IYwlKCjJOt7/9yfq66/nnUajIBrQiQ0H1TfKshFEdvDBzDOBvwY5GY7ok2OkYHXkx7Od5H/liWqAc6ShYdTphZUOHf4hPVLE="
